stages:
  get_data:
    cmd: python ./src/dataset/get_data.py
    deps:
    - ./src/dataset/get_data.py
    - pyproject.toml
    outs:
    - tmp/corpus.joblib
    - tmp/raw_labels.joblib

  data_preprocess:
    cmd: python ./src/dataset/pre_process.py
    deps:
    - ./src/dataset/pre_process.py
    - tmp/raw_labels.joblib
    - tmp/corpus.joblib
    outs:
    - tmp/corpus_processed.joblib
    - tmp/X.joblib
    - tmp/y.joblib
    - tmp/cv.joblib
    
  train:
    cmd: python ./src/modeling/train.py --seed 27 --test_size 0.3
    deps:
    - ./src/modeling/train.py
    - tmp/X.joblib
    - tmp/y.joblib
    - tmp/cv.joblib
    outs:
    - tmp/model.joblib
    - tmp/X_test.joblib
    - tmp/y_test.joblib

  evaluate:
    cmd: python ./src/modeling/evaluate.py
    deps:
    - ./src/modeling/evaluate.py
    - tmp/model.joblib
    - tmp/X_test.joblib
    - tmp/y_test.joblib
    outs:
    - metrics/metrics.json

metrics:
  - metrics/metrics.json


  