name: Linting

on: push

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -e .

      - name: Run pylint
        run: |
          pylint .

      - name: Run pylint and extract score
        id: pylint
        run: |
          OUTPUT=$(pylint src tests --exit-zero)
          echo "$OUTPUT"
          SCORE=$(echo "$OUTPUT" | grep "Your code has been rated at" | awk '{print $7}' | cut -d/ -f1)
          echo "score=$SCORE" >> $GITHUB_OUTPUT
      
      - name: Determine badge color
        id: color
        run: |
          score=${{ steps.pylint.outputs.score }}
          if awk "BEGIN {exit !($score >= 9.5)}"; then
            color="brightgreen"
          elif awk "BEGIN {exit !($score >= 8)}"; then
            color="orange"
          elif awk "BEGIN {exit !($score >= 5)}"; then
            color="yellow"
          else
            color="red"
          fi
          echo "color=$color" >> $GITHUB_OUTPUT

      - name: Generate pylint badge SVG
        run: |
          curl -o pylint-badge.svg "https://img.shields.io/badge/pylint-${{ steps.pylint.outputs.score }}-${{ steps.color.outputs.color }}.svg"

      - name: Run flake8
        run: |
          pip install -e linter_rules/flake8 --use-pep517
          flake8 .

      - name: Run bandit
        run: |
          bandit -r . -c bandit.yaml

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add pylint-badge.svg
                
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update pylint badge [skip ci]"
            git push origin HEAD:main
          fi
