name: Linting

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -e .

      - name: Run pylint
        run: |
          pylint src/dataset
          pylint src/modeling

      - name: Run flake8
        run: |
          flake8 src/dataset
          flake8 src/modeling

      - name: Run bandit
        run: |
          bandit -r src/dataset
          bandit -r src/modeling