name: Linting

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -e .

      - name: Run pylint
        run: |
          pylint src
          pylint tests

      - uses: Silleellie/pylint-github-action@v2.1
        with:
          lint-path: |
            src
            tests
          python-version: 3.11
          pylintrc-path: pylintrc

      - name: Run flake8
        run: |
          pip install -e linter_rules/flake8 --use-pep517
          flake8 .

      - name: Run bandit
        run: |
          bandit -r . -c bandit.yaml