name: ML Testing

on: push

jobs:
    test:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              
            - name: Set up Python 3.11
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'

            - name: Install dependencies
              run: |
                  pip install -e .

            # Saving as XML and txt to have both a human-readable and machine-readable format available
            - name: Run tests with pytest and coverage
              run: |
                  pytest --cov=src --cov-report=xml --cov-report=term-missing tests/> pytest-coverage.txt
                  cat pytest-coverage.txt

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v4
              with:
                files: coverage.xml
                flags: unittests
                name: codecov-ml
